"""empty message

Revision ID: 07d30ddfa6c0
Revises: 8f8a3a1cf164
Create Date: 2020-06-24 22:25:03.682363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d30ddfa6c0'
down_revision = '8f8a3a1cf164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acts', 'id')
    op.drop_column('actors','gender')
    op.add_column("actors",sa.Column("gender",sa.CHAR(length=1),nullable=False))
    op.create_primary_key(
            "pk_acts", "acts",
            ["actor_id", "movie_id"]
        )         
    # ### end Alembic commands ###
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acts', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
