"""empty message

Revision ID: 8f8a3a1cf164
Revises: edaad3bf12bc
Create Date: 2020-06-24 16:41:30.323405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f8a3a1cf164'
down_revision = 'edaad3bf12bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'release_date')
    op.add_column('movies', sa.Column('release_date', sa.Date(), nullable=False))
             
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
