"""empty message

Revision ID: edaad3bf12bc
Revises: ff2655cb3949
Create Date: 2020-06-23 21:57:21.168155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edaad3bf12bc'
down_revision = 'ff2655cb3949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'age')
    # ### end Alembic commands ###
